recipes.remove(<avaritia:resource>);
recipes.remove(<avaritia:resource:1>);
recipes.remove(<avaritia:extreme_crafting_table>);

mods.avaritia.ExtremeCrafting.remove(<avaritia:neutron_collector>);
mods.avaritia.ExtremeCrafting.addShaped("sootcoverdmachinecase",<deepmoblearning:machine_casing>,[[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_redstone>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_plate>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_redstone>,<contenttweaker:elementlu>,<contenttweaker:elementdr>,<deepmoblearning:soot_covered_plate>,<contenttweaker:elementdr>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<contenttweaker:elementlu>,<contenttweaker:elementdr>,<contenttweaker:selementts>,<deepmoblearning:soot_covered_plate>,<contenttweaker:selementts>,<contenttweaker:elementdr>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<contenttweaker:elementlu>,<contenttweaker:elementdr>,<contenttweaker:selementts>,<deepmoblearning:soot_covered_plate>,<contenttweaker:selementts>,<contenttweaker:elementdr>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_redstone>,<contenttweaker:elementlu>,<contenttweaker:elementdr>,<deepmoblearning:soot_covered_plate>,<contenttweaker:elementdr>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_redstone>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_plate>,<contenttweaker:elementlu>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_redstone>,<deepmoblearning:soot_covered_plate>],[<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>,<deepmoblearning:soot_covered_plate>]]);
mods.extendedcrafting.TableCrafting.addShaped(0, <eternalsingularity:eternal_singularity>, [	[null, <avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, null, null, <avaritia:resource:4>, <avaritia:resource:4>, null], 	[<avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, null, null, <avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>], 	[<avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>], 	[null, <avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, null, <ore:ingotInfinitycatalyst>], 	[null, null, <avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <extendedcrafting:singularity_ultimate>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>, null, null], [<ore:ingotInfinitycatalyst>, null, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>, null], 	[<ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>], 	[<avaritia:resource:4>, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>, null, null, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>], 	[null, <avaritia:resource:4>, <avaritia:resource:4>, null, null, <ore:ingotInfinitycatalyst>, <ore:ingotInfinitycatalyst>, <avaritia:resource:4>, null]]);
mods.avaritia.ExtremeCrafting.remove(<eternalsingularity:eternal_singularity>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
mods.extendedcrafting.EnderCrafting.remove(<extendedcrafting:material:40>);
mods.extendedcrafting.EnderCrafting.addShaped(<avaritia:extreme_crafting_table>, [	[<avaritia:double_compressed_crafting_table>, <avaritia:double_compressed_crafting_table>, <avaritia:double_compressed_crafting_table>], 	[<ore:blockCrystalMatrix>, <extendedcrafting:table_ultimate>, <ore:blockCrystalMatrix>], 	[<ore:blockCrystalMatrix>, <ore:blockCrystalMatrix>, <ore:blockCrystalMatrix>]]);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:5>);
mods.avaritia.ExtremeCrafting.remove(<avaritia:resource:6>);
recipes.remove(<avaritia:resource:4>);
mods.avaritia.Compressor.remove(<avaritia:singularity>);
mods.avaritia.Compressor.remove(<avaritia:singularity:1>);
mods.avaritia.Compressor.remove(<avaritia:singularity:2>);
mods.avaritia.Compressor.remove(<avaritia:singularity:3>);
mods.avaritia.Compressor.remove(<avaritia:singularity:4>);
mods.avaritia.Compressor.remove(<avaritia:singularity:5>);
mods.avaritia.Compressor.remove(<avaritia:singularity:6>);
mods.avaritia.Compressor.remove(<avaritia:singularity:7>);
mods.avaritia.Compressor.remove(<avaritia:singularity:8>);
mods.avaritia.Compressor.remove(<avaritia:singularity:9>);
mods.avaritia.Compressor.remove(<avaritia:singularity:10>);
mods.avaritia.Compressor.remove(<avaritia:singularity:11>);



