recipes.addShaped(<contenttweaker:bulatsteelrod>, [	[null, <contenttweaker:bulatsteelingot>, null], 	[null, <contenttweaker:bulatsteelingot>, <contenttweaker:wrench>.anyDamage().transformDamage(0)], 	[null, <contenttweaker:bulatsteelingot>, null]]);
recipes.addShaped(<contenttweaker:bulatfiberreinforcedcircuitboard>, [	[<contenttweaker:longbulatsteelrod>, <ore:ingotDarkSteel>, <contenttweaker:longbulatsteelrod>], 	[<contenttweaker:longbulatsteelrod>, <gregtech:meta_item_2:32445>, <contenttweaker:longbulatsteelrod>], 	[<contenttweaker:longbulatsteelrod>, <ore:ingotDarkSteel>, <contenttweaker:longbulatsteelrod>]]);
recipes.addShaped(<contenttweaker:catalyst>, [	[<ore:dustTinySilicon>, null, <ore:dustTinySilicon>], 	[<ore:dustSmallCalcium>, <ore:dustSmallAluminium>, <ore:dustSmallCalcium>], 	[null, <ore:dustSmallCalcium>, null]]);
recipes.addShaped(<contenttweaker:lasercrystal>, [	[null, <gregtech:meta_item_1:12154>, null], 	[<gregtech:meta_item_2:32572>, <gregtech:meta_item_1:12154>, <gregtech:meta_item_2:32572>], 	[null, <gregtech:meta_item_2:32572>, null]]);
recipes.addShaped(<contenttweaker:lasermodule>, [	[<contenttweaker:lasercrystal>, <ore:stickRuby>, <ore:plateRubber>], 	[<ore:stickRuby>, <contenttweaker:lasercrystal>, <ore:ingotRubber>], 	[<ore:plateRubber>, <ore:ingotRubber>, <ore:ringRubber>]]);
recipes.addShaped(<contenttweaker:wrench>, [	[<ore:ingotSteel>, null, <ore:ingotSteel>], 	[null, <ore:ingotSteel>, null], 	[null, <ore:ingotSteel>, null]]);
recipes.addShaped(<contenttweaker:silversteelrod>, [	[null, null, null], 	[null, <contenttweaker:silversteel>, null], 	[null, <contenttweaker:silversteel>, null]]);
recipes.addShaped(<contenttweaker:electricalsteelrod>, [	[null, null, null], 	[null, <ore:ingotElectricalSteel>, null], 	[null, <ore:ingotElectricalSteel>, null]]);
recipes.addShaped(<contenttweaker:electricalsteelgear>, [	[<contenttweaker:electricalsteelrod>, <contenttweaker:electricalsteelplate>, <contenttweaker:electricalsteelrod>], 	[<contenttweaker:electricalsteelplate>, <contenttweaker:wrench>.transformDamage(0), <contenttweaker:electricalsteelplate>], 	[<contenttweaker:electricalsteelrod>, <contenttweaker:electricalsteelplate>, <contenttweaker:electricalsteelrod>]]);
recipes.addShaped(<contenttweaker:silversteelgear>, [	[<contenttweaker:silversteelrod>, <contenttweaker:silversteelplate>, <contenttweaker:silversteelrod>], 	[<contenttweaker:silversteelplate>, <contenttweaker:wrench>.transformDamage(0), <contenttweaker:silversteelplate>], 	[<contenttweaker:silversteelrod>, <contenttweaker:silversteelplate>, <contenttweaker:silversteelrod>]]);
recipes.addShaped(<contenttweaker:longsilversteelrod>, [	[null, <contenttweaker:silversteelrod>, null], 	[null, <contenttweaker:silversteelrod>, null], 	[null, <contenttweaker:silversteelrod>, null]]);
recipes.addShaped(<contenttweaker:longelectricalsteelrod>, [	[null, <contenttweaker:electricalsteelrod>, null], 	[null, <contenttweaker:electricalsteelrod>, null], 	[null, <contenttweaker:electricalsteelrod>, null]]);
recipes.addShaped(<contenttweaker:longbulatsteelrod>, [	[null, <contenttweaker:bulatsteelrod>, null], 	[null, <contenttweaker:bulatsteelrod>, null], 	[null, <contenttweaker:bulatsteelrod>, null]]);
recipes.addShaped(<contenttweaker:advancedalloygear>, [	[null, <gregtech:meta_item_2:32433>, null], 	[<gregtech:meta_item_2:32433>, <contenttweaker:wrench>, <gregtech:meta_item_2:32433>], 	[null, <gregtech:meta_item_2:32433>, null]]);
recipes.addShaped(<contenttweaker:electricalsteelgear>, [	[null, <enderio:block_alloy>, null], 	[<enderio:block_alloy>,<contenttweaker:hammer>.anyDamage().transformDamage(0),<enderio:block_alloy>], 	[null, <enderio:block_alloy>, null]]);
recipes.addShaped(<contenttweaker:stoneknife>, [	[<ore:stoneCobble>, null, null], 	[null, <ore:stoneCobble>, null], 	[null, null, <ore:stickWood>]]);
recipes.addShaped(<gtadditions:ga_dust:32154> * 4, [	[<ore:dustCopper>, <ore:dustCopper>, <ore:dustCopper>], 	[<ore:dustCopper>, <ore:dustTin>, <ore:dustTin>], 	[null, null, null]]);
recipes.addShaped(<contenttweaker:hammer>, [	[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], 	[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], 	[null, <ore:stickLongWood>, null]]);
recipes.addShaped(<contenttweaker:stretchedwool>, [	[<ore:stickWood>, <ore:wool>, <ore:stickWood>], 	[<ore:boltWood>, <ore:paper>, <ore:boltWood>], 	[<ore:stickWood>, <ore:wool>, <ore:stickWood>]]);
recipes.addShaped(<contenttweaker:woodgear>, [	[<ore:dustWood>, <ore:stickWood>, <ore:dustWood>], 	[<ore:stickWood>, <ore:logWood>, <ore:stickWood>], 	[<ore:dustWood>, <ore:stickWood>, <ore:dustWood>]]);
recipes.addShaped(<contenttweaker:woodeningotmold>, [	[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], 	[<ore:plankWood>, <ore:ingotIron>, <ore:plankWood>],     [<ore:plankWood>, <contenttweaker:woodgear>, <ore:plankWood>]]);
recipes.addShaped(<contenttweaker:unfiredfireclaybrick> * 4, [	[<gregtech:meta_item_2:32014>, <gregtech:meta_item_2:32014>, <gregtech:meta_item_2:32014>], 	[<gregtech:meta_item_2:32014>, <contenttweaker:woodeningotmold>.transformDamage(0), <gregtech:meta_item_2:32014>], 	[<gregtech:meta_item_2:32014>, <gregtech:meta_item_2:32014>, <gregtech:meta_item_2:32014>]]);
recipes.addShaped(<contenttweaker:electricalsteelplate>, [	[null, <gregtech:meta_tool:6>, null], 	[null, <ore:ingotElectricalSteel>, null], 	[null, <ore:ingotElectricalSteel>, null]]);
recipes.addShaped(<contenttweaker:engine>, [	[<ore:gearElectrum>, <minecraft:clock>, <ore:gearElectrum>], 	[<ore:gearSmallSteel>, <minecraft:wooden_pressure_plate>, <ore:gearSmallSteel>], 	[<ore:circuitBasic>, <ore:gearSmallSteel>, <ore:circuitBasic>]]);
recipes.addShapeless(<contenttweaker:compressedironnugget>*9, [<ore:ingotIronCompressed>]);
recipes.addShaped(<contenttweaker:hvroboticcomponent>, [	[<gregtech:meta_item_1:32651>, <gregtech:meta_item_1:32641>, <contenttweaker:electricalsteelrod>], 	[<ore:stickKanthal>, <ore:plateKanthal>, <gregtech:meta_item_1:32511>], 	[null, <ore:plateKanthal>, <gregtech:meta_item_1:32641>]]);
recipes.addShaped(<contenttweaker:perciseelectronicunitcasing>, [	[<ore:plateIncoloyMa>, <ore:plateNaquadriatictritanium>, <ore:plateIncoloyMa>], 	[<gregtech:meta_item_1:32657>, <ore:frameGtTitanSteel>, <gregtech:meta_item_1:32657>], [<ore:plateIncoloyMa>, <ore:plateNaquadriatictritanium>, <ore:plateIncoloyMa>]]);
recipes.addShapeless(<gtadditions:ga_dust:32013>*2,[<gregtech:meta_item_1:2012>,<gregtech:meta_item_1:2033>,<gregtech:meta_item_1:2033>,<gregtech:meta_item_1:2033>]);
recipes.addShapeless(<gtadditions:ga_dust:32014> * 6,[<gregtech:meta_item_1:2184>,<gregtech:meta_item_1:2184>,<gregtech:meta_item_1:2184>,<gregtech:meta_item_1:2184>,<gregtech:meta_item_1:2184>,<gregtech:meta_item_1:2184>,<gregtech:meta_item_1:2062>,<gregtech:meta_item_1:2062>]);
recipes.addShaped(<contenttweaker:neutronsensor>, [	[<ore:platePlatinum>, <ore:plateDoubleRhodium>, <ore:platePlatinum>], 	[<ore:platePlatinum>, <ore:frameGtGrisium>, <ore:platePlatinum>], 	[<ore:platePlatinum>, <contenttweaker:space_warper_core>, <ore:platePlatinum>]]);
recipes.addShaped(<contenttweaker:neutronaccelerator>, [	[<ore:gearPlatinum>, <contenttweaker:space_warper_core>, <ore:gearPlatinum>], 	[<ore:platePlutonium>, <ore:plateDenseRhodium>, <ore:platePlutonium>], 	[<gregtech:meta_item_2:32484>, <projectred-integration:gate:10>, <gregtech:meta_item_2:32484>]]);
recipes.addShaped(<contenttweaker:particleprotectioncasing>, [	[<contenttweaker:radiationproofplate>, <ore:plateTungstenCarbide>, <contenttweaker:radiationproofplate>], 	[null, <ore:frameGtHsss>, null], 	[<contenttweaker:radiationproofplate>, <ore:plateTungstenCarbide>, <contenttweaker:radiationproofplate>]]);
recipes.addShaped(<contenttweaker:bronzeelectrontube>, [	[null, <ore:plateBronze>, null], 	[<ore:plateBronze>, <ore:paneGlassColorless>, <ore:plateBronze>], 	[null, <ore:plateBronze>, null]]);
recipes.addShaped(<contenttweaker:spectrekeyhandle>, [	[<randomthings:ingredient:3>, <randomthings:ingredient:3>, null], 	[<randomthings:stableenderpearl>, <randomthings:ingredient:3>, null], 	[null, null, <randomthings:ingredient:3>]]);
recipes.addShaped(<contenttweaker:stoneknife>, [[null, null, <ore:stoneCobble>], 	[null, <ore:stoneCobble>, null], 	[<ore:stickWood>, null, null]]);
recipes.addShaped(<contenttweaker:copperalloycoilblock>, [	[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], 	[<contenttweaker:copperalloycoil>, <contenttweaker:copperalloycoil>, <contenttweaker:copperalloycoil>], 	[<ore:plateIron>, <ore:plateIron>, <ore:plateIron>]]);
recipes.addShaped(<contenttweaker:copperalloycoil>, [	[<ore:wireFineCopperalloy>, <ore:wireFineCopperalloy>, <ore:wireFineCopperalloy>], 	[<ore:wireFineCopperalloy>, <ore:stickSteel>, <ore:wireFineCopperalloy>], 	[<ore:wireFineCopperalloy>, <ore:wireFineCopperalloy>, <ore:wireFineCopperalloy>]]);
recipes.addShaped(<contenttweaker:thermalcasing>*2, [	[<ore:plateSignalum>, <ore:frameGtAluminium>, <ore:plateSignalum>], 	[<ore:plateSignalum>, <gregtech:meta_item_1:32613>, <ore:plateSignalum>], 	[<ore:plateSignalum>, <ore:frameGtAluminium>, <ore:plateSignalum>]]);
recipes.addShaped(<contenttweaker:carbonmyogel>, [	[null, <ore:voodooPoppetProtectionBurn>, null],	[<gregtech:meta_item_2:32506>, <ore:ingotDarkSteel>, <gregtech:meta_item_2:32506>], 	[<gregtech:meta_item_2:32506>, <ore:ingotDarkSteel>, <gregtech:meta_item_2:32506>]]);
recipes.addShaped(<contenttweaker:wiring>*4, [	[<ore:wireGtSingleCopper>, <ore:wireGtSingleCopper>, <ore:wireGtSingleCopper>], 	[<ore:wireGtSingleCopper>, null, <ore:wireGtSingleCopper>], 	[<ore:wireGtSingleCopper>, <ore:wireGtSingleCopper>, <ore:wireGtSingleCopper>]]);
recipes.addShaped(<contenttweaker:solenoid>*2, [	[<contenttweaker:wiring>, <contenttweaker:wiring>, <contenttweaker:wiring>], 	[<contenttweaker:wiring>, <ore:stickSteel>, <contenttweaker:wiring>], 	[<contenttweaker:wiring>, <contenttweaker:wiring>, <contenttweaker:wiring>]]);
recipes.addShaped(<contenttweaker:coolantcontainmentcell>, [	[<ore:plateBlackSteel>, <ore:plateNickelZincFerrite>, <ore:plateBlackSteel>], 	[<ore:plateBlackSteel>, <gregtech:meta_item_1:32406>, <ore:plateBlackSteel>], 	[<ore:plateBlackSteel>, <ore:plateNickelZincFerrite>, <ore:plateBlackSteel>]]);
recipes.addShaped(<contenttweaker:pbistrengthenedtetrixcasing>, [	[<ore:platePolybenzimidazole>, <ore:plateFullerenePolymerMatrix>, <ore:platePolybenzimidazole>], 	[<ore:platePolybenzimidazole>, <ore:frameGtFullerenepolymertetrix>, <ore:platePolybenzimidazole>], 	[<ore:platePolybenzimidazole>, <ore:plateFullerenePolymerMatrix>, <ore:platePolybenzimidazole>]]);
recipes.addShapeless(<contenttweaker:tinyoranorhodiumcatalystdust>*9,[<gtadditions:ga_dust:32087>]);
recipes.addShaped(<contenttweaker:obsidianrod>, [	[null, null, null], 	[null, <ore:obsidian>, null], 	[null, <ore:obsidian>, null]]);
recipes.addShaped(<contenttweaker:obsidianrod>, [ 	[null, <ore:obsidian>, null], 	[null, <ore:obsidian>, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:space_warper_core>, [	[<contenttweaker:bulatsteelplate>, <ore:plateBlackSteel>, <contenttweaker:bulatsteelplate>], 	[<ore:plateBlackSteel>, <ore:craftingLensBlue>, <ore:plateBlackSteel>], 	[<contenttweaker:bulatsteelplate>, <ore:plateBlackSteel>, <contenttweaker:bulatsteelplate>]]);
recipes.addShaped(<contenttweaker:climateproofcasing>, [	[<contenttweaker:bulatsteelplate>, <ore:stickAluminium>, <contenttweaker:bulatsteelplate>], 	[<contenttweaker:supercooledplate>, <ore:frameGtBlackSteel>, <contenttweaker:supercooledplate>], 	[<ore:plateInvar>, <ore:stickAluminium>, <ore:plateInvar>]]);
recipes.addShaped(<contenttweaker:lightlytreatedwoodplanks>*4, [	[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], 	[<ore:plankWood>, <forge:bucketfilled>.withTag({FluidName: "creosote", Amount: 1000}), <ore:plankWood>], 	[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<contenttweaker:steelborderedwoodencasing>*2, [	[<ore:boltSteel>, <ore:stickLongWood>, <ore:boltSteel>], 	[<ore:stickIron>, <contenttweaker:lightlytreatedwoodplanks>, <ore:stickIron>], 	[<ore:boltSteel>, <ore:stickLongWood>, <ore:boltSteel>]]);
recipes.addShaped(<contenttweaker:detectiondevice>, [[<minecraft:comparator>, <ore:plateRedAlloy>, <minecraft:comparator>], [<ore:plateRedAlloy>, <ore:stoneSmooth>, <ore:plateRedAlloy>], 	[<minecraft:comparator>, <ore:plateRedAlloy>, <minecraft:comparator>]]);
furnace.addRecipe(<contenttweaker:blockgraphite>,<gregtech:meta_block_compressed_6:5>);
furnace.addRecipe(<contenttweaker:rubyingot>,<gregtech:meta_item_1:2154>);
furnace.addRecipe(<gtadditions:ga_dust:32007>, <contenttweaker:cryoliteore>);
recipes.addShaped(<contenttweaker:treatedwoodplanks>*8, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], 	[<ore:plankWood>, <contenttweaker:paraffinwax>, <ore:plankWood>], 	[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
recipes.addShaped(<contenttweaker:steel_plated_workbench>,[[<ore:plateSteel>,null,<ore:plateSteel>],[null,<minecraft:crafting_table>,null],[<ore:plateSteel>,null,<ore:plateSteel>]]);







