import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDict;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.block.IBlockDefinition;
import crafttweaker.block.IBlockProperties;
import crafttweaker.block.IBlock;





recipes.remove(<gregtech:machine:2>);
recipes.remove(<gregtech:machine:3>);
recipes.remove(<gregtech:machine:4>);
recipes.remove(<gregtech:machine:6>);
recipes.remove(<gregtech:machine:7>);
recipes.remove(<gregtech:machine:8>);
recipes.remove(<gregtech:machine:9>);
recipes.remove(<gregtech:machine:10>);
recipes.remove(<gregtech:machine:11>);
recipes.remove(<gregtech:machine:12>);
recipes.remove(<gregtech:machine:13>);
recipes.remove(<gregtech:machine:14>);
recipes.remove(<gregtech:machine:15>);
recipes.remove(<gregtech:machine:16>);
recipes.remove(<gregtech:machine:17>);
recipes.remove(<gregtech:machine:18>);
recipes.remove(<appliedenergistics2:material:40>);
recipes.remove(<enderio:item_material:9>);
recipes.remove(<enderio:item_material:10>);
recipes.remove(<gregtech:meta_item_1:2095>);
recipes.remove(<gregtech:frame_wood>);
recipes.remove(<enderio:item_material>);
recipes.remove(<minecraft:paper>);
recipes.remove(<gregtech:meta_item_2:32443>);
recipes.remove(<minecraft:furnace>);
recipes.remove(<minecraft:bed>);
recipes.remove(<minecraft:bed:1>);
recipes.remove(<minecraft:bed:2>);
recipes.remove(<minecraft:bed:3>);
recipes.remove(<minecraft:bed:4>);
recipes.remove(<minecraft:bed:5>);
recipes.remove(<minecraft:bed:6>);
recipes.remove(<minecraft:bed:7>);
recipes.remove(<minecraft:bed:8>);
recipes.remove(<minecraft:bed:9>);
recipes.remove(<minecraft:bed:10>);
recipes.remove(<minecraft:bed:11>);
recipes.remove(<minecraft:bed:12>);
recipes.remove(<minecraft:bed:13>);
recipes.remove(<minecraft:bed:14>);
recipes.remove(<minecraft:bed:15>);
recipes.remove(<gregtech:meta_item_2:19196>);
recipes.remove(<enderio:block_simple_alloy_smelter>);
recipes.remove(<gregtech:meta_item_2:32455>);
recipes.remove(<gregtech:meta_item_2:32454>);
recipes.remove(<gregtech:meta_item_2:32450>);
recipes.remove(<gregtech:machine:510>);
recipes.remove(<gregtech:metal_casing:1>);
recipes.remove(<appliedenergistics2:grindstone>);
recipes.remove(<gregtech:cable:5237>);
recipes.remove(<gregtech:cable:5035>);
recipes.remove(<gregtech:cable:5079>);
recipes.remove(<gregtech:cable:5071>);
recipes.remove(<gregtech:cable:5180>);
recipes.remove(<gregtech:cable:5017>);
recipes.remove(<gregtech:meta_item_1:2126>);
recipes.remove(<gregtech:machine:70>);
recipes.remove(<gregtech:machine:420>);
recipes.remove(<gregtech:machine:190>);
recipes.remove(<gregtech:machine:370>);
recipes.remove(<gregtech:machine:320>);
recipes.remove(<gregtech:machine:300>);
recipes.remove(<gregtech:machine:210>);
recipes.remove(<gregtech:machine:811>);
recipes.remove(<enderio:block_tank>);
recipes.remove(<hotornot:mitts>);
recipes.remove(<gregtech:meta_item_1:2109>);
recipes.remove(<gregtech:wire_coil>);
recipes.remove(<gregtech:machine:100>);
recipes.remove(<enderio:item_material:22>);
recipes.remove(<enderio:item_material:22>);
recipes.remove(<gregtech:machine:710>);
recipes.remove(<gregtech:machine:711>);
recipes.remove(<gregtech:machine:712>);
recipes.remove(<gregtech:machine:713>);
recipes.remove(<gregtech:machine:724>);
recipes.remove(<gregtech:frame_invar>);
recipes.remove(<gregtech:machine:511>);
recipes.remove(<gregtech:meta_item_1:2238>);
recipes.remove(<gregtech:meta_item_1:32680>);
recipes.remove(<extendedcrafting:material>);
recipes.remove(<gregtech:machine:430>);
recipes.remove(<gregtech:machine:526>);
recipes.remove(<gregtech:machine:825>);
recipes.remove(<extendedcrafting:material:36>);
recipes.remove(<enderio:item_material:51>);
recipes.remove(<enderio:block_vat>);
recipes.remove(<extendedcrafting:material:7>);
recipes.remove(<extendedcrafting:material:14>);
recipes.remove(<extendedcrafting:material:8>);
recipes.remove(<gregtech:meta_item_1:2183>);
recipes.remove(<extendedcrafting:table_basic>);
recipes.remove(<gregtech:machine:514>);
recipes.remove(<gregtech:machine:60>);
recipes.remove(<gregtech:machine:191>);
recipes.remove(<gregtech:cable:7035>);
recipes.remove(<gregtech:machine:101>);
recipes.remove(<gregtech:meta_item_1:2192>);
recipes.remove(<gregtech:meta_item_1:2127>);
recipes.remove(<gregtech:meta_item_1:2301>);
recipes.remove(<gregtech:meta_item_1:2302>);
recipes.remove(<thermalexpansion:machine:3>);
recipes.remove(<enderio:block_simple_alloy_smelter>);
recipes.remove(<enderio:block_alloy_smelter>);
recipes.remove(<enderio:block_enhanced_alloy_smelter>);
recipes.remove(<gregtech:machine:812>);
recipes.remove(<gregtech:machine:813>);
recipes.remove(<gregtech:cable:7017>);
recipes.remove(<gregtech:machine:130>);
recipes.remove(<gregtech:machine:527>);
recipes.remove(<gregtech:machine:180>);
recipes.remove(<gregtech:machine:181>);
recipes.remove(<gregtech:machine:211>);
recipes.remove(<gregtech:wire_coil:1>);
recipes.remove(<minecraft:compass>);
recipes.remove(<thermalexpansion:dynamo>);
recipes.remove(<gregtech:meta_item_1:2230>);
recipes.remove(<gregtech:meta_item_1:2094>);
recipes.remove(<gregtech:machine:2534>);
recipes.remove(<gregtech:meta_item_1:32721>);
recipes.remove(<thermalfoundation:upgrade:1>);
recipes.remove(<thermalfoundation:upgrade:33>);
recipes.remove(<thermalfoundation:upgrade:34>);
recipes.remove(<thermalfoundation:upgrade:35>);
recipes.remove(<gregtech:meta_item_1:2364>);
recipes.remove(<gregtech:metal_casing:3>);
recipes.remove(<gregtech:machine:2535>);
recipes.remove(<forestry:worktable>);
recipes.remove(<forestry:sturdy_machine>);
recipes.remove(<gregtech:meta_item_1:32671>);
recipes.remove(<gregtech:machine:814>);
recipes.remove(<gregtech:meta_item_2:32456>);
recipes.remove(<gregtech:meta_item_1:32682>);
recipes.remove(<gregtech:machine:432>);
recipes.remove(<gregtech:metal_casing:4>);
recipes.remove(<storagedrawers:controller>);
recipes.remove(<storagedrawers:compdrawers>);
recipes.remove(<extendedcrafting:table_advanced>);
recipes.remove(<gregtech:machine:2221>);
recipes.remove(<gtadditions:ga_meta_item:32572>);
recipes.remove(<thermalfoundation:upgrade>);
recipes.remove(<thermalexpansion:augment:513>);
recipes.remove(<gregtech:meta_item_1:2233>);
recipes.remove(<gregtech:meta_item_1:2231>);
recipes.remove(<gregtech:meta_item_1:2229>);
recipes.remove(<minecraft:iron_ingot> * 8);
recipes.remove(<thermalexpansion:machine:14>);
recipes.remove(<gregtech:meta_item_1:2423>);
recipes.remove(<gregtech:machine:2502>);
recipes.remove(<gregtech:meta_item_1:2304>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<appliedenergistics2:drive>);
recipes.remove(<ironchest:iron_chest>);
recipes.remove(<thermalexpansion:frame>);
recipes.remove(<thermalexpansion:capacitor>);
recipes.remove(<thermalexpansion:capacitor:1>);
recipes.remove(<appliedenergistics2:inscriber>);
recipes.remove(<extendedcrafting:material:9>);
recipes.remove(<extendedcrafting:material:16>);
recipes.remove(<extendedcrafting:material:10>);
recipes.remove(<extendedcrafting:table_elite>);
recipes.remove(<appliedenergistics2:material:43>);
recipes.remove(<appliedenergistics2:material:44>);
recipes.remove(<minecraft:piston>);
recipes.remove(<gregtech:meta_item_1:2228>);
recipes.remove(<thermalfoundation:storage_alloy:6>);
recipes.remove(<thermalfoundation:storage_alloy:5>);
recipes.remove(<appliedenergistics2:material:9>);
recipes.remove(<appliedenergistics2:part:380>);
recipes.remove(<appliedenergistics2:part:460>);
recipes.remove(<thermalexpansion:capacitor:2>);
recipes.remove(<minecraft:flint_and_steel>);
recipes.remove(<gregtech:meta_item_1:14297>);
recipes.remove(<thermalfoundation:material:136>);
recipes.remove(<thermalfoundation:material:165>);
recipes.remove(<thermalfoundation:material:166>);
recipes.remove(<appliedenergistics2:part:360>);
recipes.remove(<appliedenergistics2:part:180>);
recipes.remove(<appliedenergistics2:condenser>);
recipes.remove(<gregtech:machine:230>);
recipes.remove(<gregtech:machine:240>);
recipes.remove(<modularmachinery:itemmodularium>);
recipes.remove(<gregtech:machine:2536>);
recipes.remove(<thermalexpansion:frame:64>);
recipes.remove(<minecraft:stone_button>);
recipes.remove(<minecraft:nether_star>);
recipes.remove(<thermalexpansion:cell>);
recipes.remove(<thermalexpansion:frame:128>);














mods.jei.JEI.removeAndHide(<nuclearcraft:fluid_sulfuric_acid>);
mods.jei.JEI.removeAndHide(<libvulpes:productgear:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productgear:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productboule:3>);
mods.jei.JEI.removeAndHide(<libvulpes:productsheet:1>);
mods.jei.JEI.removeAndHide(<libvulpes:productsheet:4>);
mods.jei.JEI.removeAndHide(<libvulpes:productsheet:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productsheet:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productsheet:9>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:1>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:2>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:3>);
mods.jei.JEI.removeAndHide(<libvulpes:productrod:1>);
mods.jei.JEI.removeAndHide(<libvulpes:productrod:4>);
mods.jei.JEI.removeAndHide(<libvulpes:productrod:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productrod:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productrod:10>);
mods.jei.JEI.removeAndHide(<libvulpes:productfan:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:1>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:2>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:3>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:4>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:5>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:9>);
mods.jei.JEI.removeAndHide(<libvulpes:productdust:10>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:4>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:5>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:9>);
mods.jei.JEI.removeAndHide(<libvulpes:productplate:10>);
mods.jei.JEI.removeAndHide(<libvulpes:ore0:4>);
mods.jei.JEI.removeAndHide(<libvulpes:ore0:5>);
mods.jei.JEI.removeAndHide(<libvulpes:ore0:8>);
mods.jei.JEI.removeAndHide(<libvulpes:ore0:9>);
mods.jei.JEI.removeAndHide(<libvulpes:ore0:10>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:3>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:4>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:5>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:9>);
mods.jei.JEI.removeAndHide(<libvulpes:productnugget:10>);
mods.jei.JEI.removeAndHide(<forestry:wood_pulp>);
mods.jei.JEI.removeAndHide(<libvulpes:forgepowerinput>);
mods.jei.JEI.removeAndHide(<libvulpes:forgepoweroutput>);
mods.jei.JEI.removeAndHide(<libvulpes:coalgenerator>);
mods.jei.JEI.removeAndHide(<libvulpes:gtplug>);
mods.jei.JEI.removeAndHide(<libvulpes:battery>);
mods.jei.JEI.removeAndHide(<libvulpes:battery:1>);
mods.jei.JEI.removeAndHide(<libvulpes:creativepowerbattery>);
mods.jei.JEI.removeAndHide(<advancedrocketry:rollingmachine>);
mods.jei.JEI.removeAndHide(<advancedrocketry:platepress>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:3>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:4>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:5>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:6>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:7>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:9>);
mods.jei.JEI.removeAndHide(<libvulpes:productingot:10>);
mods.jei.JEI.removeAndHide(<libvulpes:metal0:4>);
mods.jei.JEI.removeAndHide(<libvulpes:metal0:5>);
mods.jei.JEI.removeAndHide(<libvulpes:metal0:6>);
mods.jei.JEI.removeAndHide(<libvulpes:metal0:7>);
mods.jei.JEI.removeAndHide(<libvulpes:metal0:9>);
mods.jei.JEI.removeAndHide(<libvulpes:metal0:10>);
mods.jei.JEI.removeAndHide(<advancedrocketry:cuttingmachine>);
mods.jei.JEI.removeAndHide(<advancedrocketry:crystallizer>);
mods.jei.JEI.removeAndHide(<advancedrocketry:lathe>);
mods.jei.JEI.removeAndHide(<advancedrocketry:cuttingmachine>);
mods.jei.JEI.removeAndHide(<advancedrocketry:precisionassemblingmachine>);
mods.jei.JEI.removeAndHide(<advancedrocketry:chemicalreactor>);
mods.jei.JEI.removeAndHide(<advancedrocketry:electrolyser>);
mods.jei.JEI.removeAndHide(<advancedrocketry:precisionlaseretcher>);
mods.jei.JEI.removeAndHide(<advancedrocketry:centrifuge>);
mods.jei.JEI.removeAndHide(<libvulpes:hatch>);
mods.jei.JEI.removeAndHide(<libvulpes:hatch:1>);
mods.jei.JEI.removeAndHide(<libvulpes:hatch:2>);
mods.jei.JEI.removeAndHide(<libvulpes:hatch:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:compound:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:4>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:13>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:12>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:11>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:1>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:12>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:11>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:10>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:4>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:1>);
mods.jei.JEI.removeAndHide(<gendustry:mutagen_producer>);
mods.jei.JEI.removeAndHide(<gregtech:machine:8500>);
mods.jei.JEI.removeAndHide(<qmd:dust:3>);
mods.jei.JEI.removeAndHide(<randomthings:spectrecoil_genesis>);
mods.jei.JEI.removeAndHide(<randomthings:spectrecoil_number>);
mods.jei.JEI.removeAndHide(<randomthings:spectrecoil_ender>);
mods.jei.JEI.removeAndHide(<randomthings:spectrecoil_redstone>);
mods.jei.JEI.removeAndHide(<randomthings:spectrecoil_normal>);
mods.jei.JEI.removeAndHide(<threng:material:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:7>);
mods.jei.JEI.removeAndHide(<qmd:dust2>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:1>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:2>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:3>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:4>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:5>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:6>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:7>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:8>);
mods.jei.JEI.removeAndHide(<extrautils2:terraformer:9>);
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:furnace"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:crusher"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_pink"}));
mods.jei.JEI.removeAndHide(<extrautils2:unstableingots>);
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_lava"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_death"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_tnt"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_redstone"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_potion"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_overclock"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_ice"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_culinary"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_enchant"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_ender"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_dragonsbreath"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_slime"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_netherstar"}));
mods.jei.JEI.removeAndHide(<extrautils2:machine>.withTag({Type: "extrautils2:generator_survival"}));
mods.jei.JEI.removeAndHide(<extrautils2:quarry>);
mods.jei.JEI.removeAndHide(<extrautils2:quarryproxy>);
mods.jei.JEI.removeAndHide(<extrautils2:rainbowgenerator>);
mods.jei.JEI.removeAndHide(<extrautils2:rainbowgenerator:1>);
mods.jei.JEI.removeAndHide(<extrautils2:rainbowgenerator:2>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket:6>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket:5>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket:4>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket:3>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket:2>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket:1>);
mods.jei.JEI.removeAndHide(<extrautils2:grocket>);
mods.jei.JEI.removeAndHide(<extrautils2:filter>);
mods.jei.JEI.removeAndHide(<extrautils2:filterfluids>);
mods.jei.JEI.removeAndHide(<extrautils2:spike_wood>);
mods.jei.JEI.removeAndHide(<extrautils2:spike_stone>);
mods.jei.JEI.removeAndHide(<extrautils2:glasscutter>);
mods.jei.JEI.removeAndHide(<nuclearcraft:rtg_californium>);
mods.jei.JEI.removeAndHide(<qmd:rtg_strontium>);
mods.jei.JEI.removeAndHide(<nuclearcraft:rtg_plutonium>);
mods.jei.JEI.removeAndHide(<nuclearcraft:rtg_americium>);
mods.jei.JEI.removeAndHide(<nuclearcraft:rtg_uranium>);
mods.jei.JEI.removeAndHide(<qmd:ingot_alloy:5>);
mods.jei.JEI.removeAndHide(<qmd:ingot_alloy:3>);
mods.jei.JEI.removeAndHide(<qmd:ingot2>);
mods.jei.JEI.removeAndHide(<qmd:ingot2:1>);
mods.jei.JEI.removeAndHide(<qmd:ingot:14>);
mods.jei.JEI.removeAndHide(<qmd:ingot:12>);
mods.jei.JEI.removeAndHide(<qmd:ingot:11>);
mods.jei.JEI.removeAndHide(<qmd:ingot:10>);
mods.jei.JEI.removeAndHide(<qmd:ingot:9>);
mods.jei.JEI.removeAndHide(<qmd:ingot:8>);
mods.jei.JEI.removeAndHide(<qmd:ingot:7>);
mods.jei.JEI.removeAndHide(<qmd:ingot:6>);
mods.jei.JEI.removeAndHide(<qmd:ingot:5>);
mods.jei.JEI.removeAndHide(<qmd:ingot:3>);
mods.jei.JEI.removeAndHide(<qmd:ingot:4>);
mods.jei.JEI.removeAndHide(<qmd:ingot:2>);
mods.jei.JEI.removeAndHide(<qmd:ingot:1>);
mods.jei.JEI.removeAndHide(<qmd:ingot:13>);
mods.jei.JEI.removeAndHide(<qmd:ingot>);
mods.jei.JEI.removeAndHide(<qmd:dust:10>);
mods.jei.JEI.removeAndHide(<qmd:dust2:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:fission_dust:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:fission_dust:1>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:9>);
mods.jei.JEI.removeAndHide(<qmd:ingot_alloy:2>);
mods.jei.JEI.removeAndHide(<qmd:dust>);
mods.jei.JEI.removeAndHide(<nuclearcraft:compound:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:compound:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:2>);
mods.jei.JEI.removeAndHide(<qmd:dust2:3>);
mods.jei.JEI.removeAndHide(<qmd:ingot_alloy>);
mods.jei.JEI.removeAndHide(<nuclearcraft:alloy:5>);
mods.jei.JEI.removeAndHide(<qmd:ingot_alloy:4>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:10>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:5>);
mods.jei.JEI.removeAndHide(<qmd:dust2:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:gem_dust:10>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:9>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:4>);
mods.jei.JEI.removeAndHide(<gregtech:meta_item_2:32496>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:8>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust:8>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:1>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:4>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:9>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:9>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:8>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:8>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:13>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:12>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:12>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:10>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block:11>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot_block>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:7>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:6>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:5>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:3>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:2>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore:1>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ore>);
mods.jei.JEI.removeAndHide(<nuclearcraft:water_source_dense>);
mods.jei.JEI.removeAndHide(<nuclearcraft:water_source_compact>);
mods.jei.JEI.removeAndHide(<nuclearcraft:water_source>);
mods.jei.JEI.removeAndHide(<nuclearcraft:nitrogen_collector_dense>);
mods.jei.JEI.removeAndHide(<nuclearcraft:nitrogen_collector_compact>);
mods.jei.JEI.removeAndHide(<nuclearcraft:nitrogen_collector>);
mods.jei.JEI.removeAndHide(<nuclearcraft:cobblestone_generator_dense>);
mods.jei.JEI.removeAndHide(<nuclearcraft:cobblestone_generator_compact>);
mods.jei.JEI.removeAndHide(<nuclearcraft:cobblestone_generator>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:quartz_block>);
mods.jei.JEI.removeAndHide(<gregtech:meta_block_compressed_35:1>);
mods.jei.JEI.removeAndHide(<gregtech:meta_item_1:10561>);
mods.jei.JEI.removeAndHide(<thaumcraft:nugget:2>);
mods.jei.JEI.removeAndHide(<thaumcraft:nugget:1>);
mods.jei.JEI.removeAndHide(<thaumcraft:nugget>);
mods.jei.JEI.removeAndHide(<gregtech:meta_item_1:9523>);
mods.jei.JEI.removeAndHide(<gregtech:meta_block_compressed_32:11>);
mods.jei.JEI.removeAndHide(<thaumcraft:plate>);
mods.jei.JEI.removeAndHide(<thaumcraft:plate:1>);
mods.jei.JEI.removeAndHide(<deepmoblearning:extraction_chamber>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockcasing:3>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockfluidinputhatch:1>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockfluidinputhatch>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockcasing:1>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockcasing:2>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:7>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:6>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:5>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:4>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:3>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockcasing>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockoutputbus>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:2>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch:1>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockoutputbus:1>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockenergyoutputhatch>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockcasing:5>);
mods.jei.JEI.removeAndHide(<modularmachinery:blockcasing:4>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:772>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:2>);
mods.jei.JEI.removeAndHide(<extendedcrafting:storage:2>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:3>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:51>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:46>);
mods.jei.JEI.removeAndHide(<enderio:block_simple_furnace>);
mods.jei.JEI.removeAndHide(<zerocore:debugtool>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:359>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:295>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:231>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:103>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_alloy:7>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:2049>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:1024>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:1025>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:167>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:129>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:256>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:257>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:258>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:273>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:288>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:448>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:320>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:323>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:401>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:402>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:416>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:432>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:433>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:496>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:497>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:400>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:369>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:324>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:336>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:337>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:352>);
mods.jei.JEI.removeAndHide(<thermalexpansion:augment:368>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:768>);
mods.jei.JEI.removeAndHide(<gtadditions:ga_meta_item:32347>);
mods.jei.JEI.removeAndHide(<gtadditions:ga_meta_item:32346>);
mods.jei.JEI.removeAndHide(<gtadditions:ga_meta_item:32571>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4217>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4218>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4219>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4220>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4221>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4222>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4223>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2213>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2214>);
mods.jei.JEI.removeAndHide(<forestry:ingot_bronze>);
mods.jei.JEI.removeAndHide(<forestry:ingot_tin>);
mods.jei.JEI.removeAndHide(<forestry:resources:2>);
mods.jei.JEI.removeAndHide(<forestry:resources:1>);
mods.jei.JEI.removeAndHide(<forestry:ingot_copper>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage:3>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage:2>);
mods.jei.JEI.removeAndHide(<forestry:resource_storage:1>);
mods.jei.JEI.removeAndHide(<forestry:gear_copper>);
mods.jei.JEI.removeAndHide(<forestry:gear_tin>);
mods.jei.JEI.removeAndHide(<forestry:gear_bronze>);
mods.jei.JEI.removeAndHide(<forestry:bottler>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2184>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2185>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2186>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2187>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2188>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2189>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2175>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2176>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2177>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2178>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2179>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2180>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2181>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:128>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:129>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:130>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:131>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:132>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:133>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:134>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:135>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:160>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:161>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:162>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:163>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:164>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:22>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:23>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:24>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:25>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:26>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:27>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:256>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:257>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:258>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:259>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:260>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:261>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:262>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:263>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:288>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:289>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:290>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:291>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:292>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:325>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:326>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:327>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:321>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:322>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:323>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:324>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:320>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:352>);
mods.jei.JEI.removeAndHide(<appliedenergistics2:material:49>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:64>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:65>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:66>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:67>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:68>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:69>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:70>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:71>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:96>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:97>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:98>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:99>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:100>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:353>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:354>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:355>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:356>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:192>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:193>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:194>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:195>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:196>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:197>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:198>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:199>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:224>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:228>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:227>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:226>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:225>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:2>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:3>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:4>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:5>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:6>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:7>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage:8>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_alloy:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_alloy>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_alloy:2>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_alloy:3>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_alloy:4>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:1>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:2>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:3>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:4>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:5>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:6>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:7>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:8>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:9>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:10>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:11>);
mods.jei.JEI.removeAndHide(<thermalexpansion:device:12>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:2>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:4>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:6>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:7>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:8>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:9>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:10>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:11>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:12>);
mods.jei.JEI.removeAndHide(<thermalexpansion:machine:13>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:2>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:3>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:4>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:5>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:6>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:7>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:8>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:9>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:10>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:11>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:12>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:13>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:14>);
mods.jei.JEI.removeAndHide(<thermalfoundation:dye:15>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:2>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:3>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:4>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:5>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:6>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore:7>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore_fluid>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore_fluid:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore_fluid:2>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore_fluid:3>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore_fluid:4>);
mods.jei.JEI.removeAndHide(<thermalfoundation:ore_fluid:5>);
mods.jei.JEI.removeAndHide(<thermalfoundation:armor.helmet_aluminum>);
mods.jei.JEI.removeAndHide(<thermalfoundation:armor.plate_aluminum>);
mods.jei.JEI.removeAndHide(<thermalfoundation:armor.legs_aluminum>);
mods.jei.JEI.removeAndHide(<thermalfoundation:armor.boots_aluminum>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:2>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:3>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:4>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:5>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:6>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:7>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:8>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:9>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:10>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:11>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:12>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:13>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:14>);
mods.jei.JEI.removeAndHide(<thermalfoundation:rockwool:15>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:16>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:33>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:32>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:17>);
mods.jei.JEI.removeAndHide(<enderio:block_simple_alloy_smelter>);
mods.jei.JEI.removeAndHide(<enderio:block_alloy_smelter>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball:1>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball:2>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball:3>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball:4>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball:5>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_endergy_ball:6>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:1>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:2>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:3>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:4>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:5>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:6>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:7>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:8>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:9>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:57>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:58>);
mods.jei.JEI.removeAndHide(<enderio:item_alloy_ball:59>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10651>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10652>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10653>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10650>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10654>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10655>);
mods.jei.JEI.removeAndHide(<extendedcrafting:crafting_table>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10656>);
mods.jei.JEI.removeAndHide(<gregtech:machine:10657>);
mods.jei.JEI.removeAndHide(<gregtech:machine:500>);
mods.jei.JEI.removeAndHide(<enderio:item_material:23>);
mods.jei.JEI.removeAndHide(<enderio:item_material:24>);
mods.jei.JEI.removeAndHide(<enderio:item_material:25>);
mods.jei.JEI.removeAndHide(<enderio:item_material:26>);
mods.jei.JEI.removeAndHide(<enderio:item_material:27>);
mods.jei.JEI.removeAndHide(<enderio:item_material:28>);
mods.jei.JEI.removeAndHide(<enderio:item_material:29>);
mods.jei.JEI.removeAndHide(<enderio:item_material:31>);
mods.jei.JEI.removeAndHide(<enderio:item_material:32>);
mods.jei.JEI.removeAndHide(<enderio:item_material:33>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4198>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4199>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4200>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4201>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4202>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4203>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4204>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4205>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4206>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4207>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4209>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4210>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4208>);
mods.jei.JEI.removeAndHide(<enderio:block_enhanced_alloy_smelter>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2235>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4175>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4176>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4177>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2278>);
mods.jei.JEI.removeAndHide(<gregtech:machine:2232>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4197>);
mods.jei.JEI.removeAndHide(<gregtech:machine:4212>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_resource>);
mods.jei.JEI.removeAndHide(<thermalfoundation:storage_resource:1>);
mods.jei.JEI.removeAndHide(<thermalfoundation:material:802>);
mods.jei.JEI.removeAndHide(<forestry:wood_pile>);
mods.jei.JEI.removeAndHide(<thermalexpansion:dynamo:5>);
mods.jei.JEI.removeAndHide(<forestry:charcoal>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot>);
mods.jei.JEI.removeAndHide(<nuclearcraft:dust>);
mods.jei.JEI.removeAndHide(<nuclearcraft:ingot:13>);
mods.jei.JEI.removeAndHide(<gregtech:machine:525>);
mods.jei.JEI.removeAndHide(<gregtech:machine:520>);
mods.jei.JEI.removeAndHide(<gregtech:machine:519>);
mods.jei.JEI.removeAndHide(<gregtech:machine:518>);
mods.jei.JEI.removeAndHide(<gregtech:machine:517>);
mods.jei.JEI.removeAndHide(<gregtech:machine:516>);
mods.jei.JEI.removeAndHide(<gregtech:machine:515>);
mods.jei.JEI.removeAndHide(<gregtech:machine:514>);
mods.jei.JEI.removeAndHide(<gregtech:machine:513>);
mods.jei.JEI.removeAndHide(<gregtech:machine:512>);
mods.jei.JEI.removeAndHide(<gregtech:machine:511>);


















mods.jei.JEI.addDescription(<contenttweaker:io>,"Planet Properties:           Veins:                            Mica, Molybdenite, Molybdenum, Monazite, Opal                     Rocket Requirement:        T5   Breathable: No                   Corrosive: No                   Atmosphere: No                    Temperature: -174.0 C, Gravity: 48%   Type : Moon, Class: Cold Selena   Day Lenght: 42h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:callisto>,"Planet Properties:     Veins:   Mica, Molybdenite, Molybdenum, Monazite, Naquadah   Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -174.0 C, Gravity: 46%   Type : Moon, Class: Cold Selena   Day Lenght: 154h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:europa>,"Planet Properties:     Veins:   Dolomite, Galena, Pitchblende, Platinum, Platinum Salt, Precious, Quartz, Tungstate  Rocket Requirement:   T5   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -174.0 C, Gravity: 38%   Type : Moon, Class: Cold Selena   Day Lenght: 58h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:ganymede>,"Planet Properties:     Veins:   Mana Infused, Molybdenum, Monazite, Mythrillium, Naquadah, Naquadah2  Rocket Requirement:   T5   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -174.0 C, Gravity: 43%   Type : Moon, Class: Cold Selena   Day Lenght: 102h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:mercury>,"Planet Properties:     Veins:   Iron, Kaolinite, Kyanite, Lapis, Lignite Coal, Magnetite, Manganese, Phosphate  Rocket Requirement:   T3   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 120.0 C, Gravity: 48%   Type : Planet, Class: Hot Selena   Day Lenght: 176h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:venus>,"Planet Properties:     Veins:   Kyanite, Olivine, Sheldonite, Uranium  Rocket Requirement:   T2   Breathable: No, Corrosive: No, Atmosphere: CO2, Nitrogen   Temperature: 150.0 C, Gravity: 62%   Type : Planet, Class: Hot Desert   Day Lenght: 720h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:moon>,"Planet Properties:     Veins:   Beryllium, Diamond, Quartz, Rutile   Rocket Requirement:   T1   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 30.0 C, Gravity: 38%   Type : Moon, Class: Comfort Selena   Day Lenght: 192h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:mars>,"Planet Properties:     Veins:   Bornite, Cassiterite, Chalcopyrite1, Chalcopyrite, Coal, Platinum, Galena, Dolomite, Diamond, Deep Iron   Rocket Requirement:   T2   Breathable: No, Corrosive: No, Atmosphere:CO2, Argon, Nitrogen   Temperature: -60.0 C, Gravity: 42%   Type : Planet, Class: Cold Desert   Day Lenght: 24h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:phobos>,"Planet Properties:     Veins:   Chalcopyrite, Coal, Deep Iron, Sodalite, Sulfur2, Talc   Rocket Requirement:   T2   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -48.0 C, Gravity: 34%   Type : Moon, Class: Cool Selena   Day Lenght: 12h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:ceres>,"Planet Properties:     Veins:   Mana Infused, Molybdenite, Nickel, Olivine2, Platinum Salt, Precious, Quartz   Rocket Requirement:   T4   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -120.0 C, Gravity: 36%   Type : Planet, Class: Cold Selena   Day Lenght: 10h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:asteroids>,"Planet Properties:     Veins:   Black Granite, Galena, Monazite, Mythrillium, Titanium Ice, Vinteum   Rocket Requirement:   T4   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -45.0 C, Gravity: 28%   Type : Asteroid, Class: Asteroid   Day Lenght: 0h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:enceladus>,"Planet Properties:     Veins:   Alumina, Apatite, Basalt, Basaltic Mineral, Beryllium, Black Granite, Bortnite, Cassiterite, Chalcopyrite1   Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -240.0 C, Gravity: 42%   Type : Moon, Class: Cold Selena   Day Lenght: 32h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:titan>,"Planet Properties:     Veins:   Nether Quartz, Titanium Ice, Tetrahedrite, Rutile, Nickel, Natural Gas Plate   Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -240.0 C, Gravity: 42%   Type : Moon, Class: Cold Selena   Day Lenght: 32h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:miranda>,"Planet Properties:     Veins:   Deep Iron, Diamond, Dolomite, Galena, Heavy Oil, High-Class Uranium, Infused Gold   Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -216.0 C, Gravity: 43%   Type : Moon, Class: Cold Selena   Day Lenght: 33h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:triton>,"Planet Properties:     Veins:   Apatite, Basalt, Basaltic Mineral, Beryllium, Black Granite, Bornite, Dolomite, Galena, Heavy Oil, High-Class Uranium, Infused Gold, Iron   Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -237.0 C, Gravity: 41%   Type : Moon, Class: Cold Selena   Day Lenght: 145h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:pluto>,"Planet Properties:     Veins:   Mythrillium, Pitchblende, Platinum Salt, Precious, Redstone, Rutile   Rocket Requirement:   T6   Breathable: No, Corrosive: No,Atmosphere: Nitrogen   Temperature: -234.0 C, Gravity: 38%   Type : Planet, Class: Cold Selena   Day Lenght: 98h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:kupiterbelt>,"Planet Properties:     Veins:   Natural Gas Plate, Netherquartz, Nickel, Oilsands, Olivine2   Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -246.0 C, Gravity: 0%   Type : Planet, Class: Cold Asteroid   Day Lenght: 0h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:haumea>,"Planet Properties:     Veins:   Dolomite, Galena, Iron, Infused Gold, High-Class Uranium, Heavy Oil    Rocket Requirement:   T6   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -249.0 C, Gravity: 33%   Type : Planet, Class: Cold Selena   Day Lenght: 12h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:barnadac>,"Planet Properties:     Veins:    Alumina, Coal, Diamond, Dolomite, Pitchblende, Sheldonite   Rocket Requirement:   T6 + Sublight   Breathable: Yes, Corrosive: No, Atmosphere: CO2, Oxygen, Argon   Temperature: 30.0 C, Gravity: 89%   Type : Planet, Class: Comfort Selena   Day Lenght: 24h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:fronos>,"Planet Properties:     Veins:    Infused Gold, Light Oil, Marble, Naquadah, Oilsands   Rocket Requirement:   T6 + Sublight   Breathable: Yes, Corrosive: No, No Atmosphere   Temperature: 30.0 C, Gravity: 0%   Type : Planet, Class: Comfort Terra   Day Lenght: 24h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:nibiru>,"Planet Properties:     Veins:    Mythrillium, Naquadah2, Naquadah, Natural Gas, Netherquartz, Nickel   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: Yes, No Atmosphere   Temperature: 30.0 C, Gravity: 87%   Type : Planet, Class: Comfort Selena   Day Lenght: 144h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:chalos>,"Planet Properties:     Veins:    Platinum Salt, Precious, Quartz, Red Granite, Redstone, Rutile   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 30.0 C, Gravity: 73%   Type : Planet, Class: Comfort Selena   Day Lenght: 48h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:diona>,"Planet Properties:     Veins:    Diamond, Dolomite, High-Class Uranium, Kaolinite, Kyanite, Mythrillium, Naquadah, Natural Gas Plate   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 30.0 C, Gravity: 35%   Type : Planet, Class: Comfort Selena   Day Lenght: 96h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:proximab>,"Planet Properties:     Veins:    Manganese, Mica, Molybdenite, Naquadah, Netherquartz, Nickel, Oilsands, Platinum, Redstone, Rutile, Sapphire, Tetrahedrite, Tin, Tungstate2, Uranium, Vinteum    Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No,Atmosphere: CO2, Oxygen   Temperature: -15.0 C, Gravity: 84%   Type : Planet, Class: Comfort Selena   Day Lenght: 175h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:taucetif>,"Planet Properties:     Veins:    Alumina, Apatite, Bornite, Chalcopyrite, Diamond, Iron, Lapis, Magnetite, Mana Infused   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: -6.0 C, Gravity: 83%   Type : Planet, Class: Comfort Selena   Day Lenght: 36h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:trappist1c>,"Planet Properties:     Veins:    Mica, Molybedenum, Monazite, Mythrillium, Naqudah2, Naqudah, Natural Gas Plate    Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 60.0 C, Gravity: 35%   Type : Planet, Class: Hot Selena   Day Lenght: 32h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:trappist1e>,"Planet Properties:     Veins:   High-Class Uranium, Infused Gold, Magnetite2, Sapphire, Sheldonite, Sodalite, Sulfur2, Talc, Tenorite, Tetrahedrite   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 150.0 C, Gravity: 35%   Type : Planet, Class: Hot Selena   Day Lenght: 24h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:yzcetib>,"Planet Properties:     Veins:    Magnetite2, Mana Infused, Manganese, Molybdenite, Monazite, Mythrillium   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 60.0 C, Gravity: 70%   Type : Planet, Class: Hot Selena   Day Lenght: 23h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:yzcetic>,"Planet Properties:     Veins:    Dolomite, Galena, High-Class Uranium, Infused Gold, kyanite, Lapis, Lignite Coal   Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 240.0 C, Gravity: 70%   Type : Planet, Class: Hot Selena   Day Lenght: 28h   Has Dungeon: Yes");
mods.jei.JEI.addDescription(<contenttweaker:yzcetid>,"Planet Properties:     Veins:    Diamond, Beryllium, Black Granite, Cassiterite, Bornite, Chalcopyrite, Coal, Deep Iron, Dolomite, Galena  Rocket Requirement:   T6 + Sublight   Breathable: No, Corrosive: No, No Atmosphere   Temperature: 60.0 C, Gravity: 63%   Type : Planet, Class: Hot Selena   Day Lenght: 35h   Has Dungeon: No");
mods.jei.JEI.addDescription(<contenttweaker:overworld>,"Planet Properties:     Veins:   Alumina, Apatite, Basaltic Mineral, Bornite, Cassiterite, Chalcopyrite, Coal, Galena, Salts, Sodalite, Tin, Manganese, Mica, Quartz, Light Oil, Lignite Coal, Lapis, Diamond,   Rocket Requirement:   T0   Breathable: Yes, Corrosive: No, Atmosphere: Nitrogen, Oxygen, Argon   Temperature: 30.0 C, Gravity: 100%   Type : Planet, Class: Comfort Terra   Day Lenght: 24h   Has Dungeon: Yes");










